### PR TITLE
bump to Xcode 11.0

### PR DESCRIPTION
**Pull request by ened**
Have not touched the simulators yet, as they are not released yet? Can update as soon as there's a official release.

### CODE REVIEW

**Comment by fkorotkov** [comment]
Yeah. Waiting for that final GM to migrate 'mojave-flutter' to Xcode 11 🙌

**Comment by ened** [comment]
Do you think there is a chance to get a Xcode 11 image going using the GM2 seed at least? That's the recommended version at this tiny window. Cirrus does have a flutter image using beta5.. was hoping we can update that one quickly?

**Comment by ened** [comment]
@fkorotkov hi - I think we are ready to bump the version?

**Comment by fkorotkov** [comment]
Yeah. `mojave-xcode-11` base image was updated to the GM over the weekend. Mergin it now and will initiate a process of building and rolling the new `mojave-xcode-11-flutter` image. Will update `mojave-flutter` image alias to the new version as well.

**Pull request merged**
